{
  CompletableFuture<Integer> initialFuture=new FlinkCompletableFuture<>();
  initialFuture.completeExceptionally(new TestException("Test exception"));
  try {
    initialFuture.get();
    fail("Get should have thrown an exception.");
  }
 catch (  ExecutionException e) {
    throw e.getCause();
  }
}
