{
  try {
    callback.onFailure(cause);
  }
 catch (  Throwable t) {
    LOG.error("Failed to notify callback about failure",t);
  }
}
